import type {
  BuildingDef,
  BuildingKey,
  DistrictKey,
  GearClass,
  GearClassDef,
  ItemDef,
  Sector,
  CombatSkill,
  CombatUnit,
  EnemyEncounterType,
} from "./types"

export const GEAR_CLASSES: Record<GearClass, GearClassDef> = {
  A: {
    cls: "A",
    name: "A-Gear",
    role: "Attacker",
    color: "var(--color-gear-a)",
    tagline: "Cận chiến áp sát, sát thương bùng nổ",
    base: { hp: 1400, attack: 210, defense: 120, speed: 95, evasion: 22, energy: 80 },
    growth: { hp: 140, attack: 26, defense: 12, speed: 4, evasion: 1.5, energy: 6 },
    strengths: ["DPS đơn mục tiêu cao nhất", "Áp sát nhanh", "Chí mạng mạnh"],
    buildCost: { credits: 1200, alloy: 400, energy: 120 },
  },
  B: {
    cls: "B",
    name: "B-Gear",
    role: "Bomber",
    color: "var(--color-gear-b)",
    tagline: "Oanh tạc diện rộng, phá công trình",
    base: { hp: 2200, attack: 180, defense: 180, speed: 55, evasion: 8, energy: 100 },
    growth: { hp: 240, attack: 22, defense: 20, speed: 2, evasion: 0.4, energy: 8 },
    strengths: ["Máu trâu nhất", "Sát thương diện rộng", "Công phá căn cứ"],
    buildCost: { credits: 1500, alloy: 620, energy: 100 },
  },
  I: {
    cls: "I",
    name: "I-Gear",
    role: "Interceptor",
    color: "var(--color-gear-i)",
    tagline: "Đánh chặn cơ động, né tránh cao",
    base: { hp: 1150, attack: 165, defense: 95, speed: 130, evasion: 40, energy: 90 },
    growth: { hp: 110, attack: 20, defense: 9, speed: 6, evasion: 2.4, energy: 7 },
    strengths: ["Tốc độ & né cao nhất", "Đánh chặn tàu mẹ", "Ra đòn trước"],
    buildCost: { credits: 1300, alloy: 360, energy: 150 },
  },
  M: {
    cls: "M",
    name: "M-Gear",
    role: "Magician / Support",
    color: "var(--color-gear-m)",
    tagline: "Hỗ trợ, hồi phục và buff hạm đội",
    base: { hp: 1300, attack: 130, defense: 110, speed: 80, evasion: 18, energy: 160 },
    growth: { hp: 120, attack: 14, defense: 11, speed: 3, evasion: 1.2, energy: 14 },
    strengths: ["Hồi máu hạm đội mỗi vòng", "Buff sát thương", "Năng lượng dồi dào"],
    buildCost: { credits: 1400, alloy: 300, energy: 200 },
  },
}

export const GEAR_ORDER: GearClass[] = ["A", "B", "I", "M"]

const commonSkills = (gear: GearClass, skills: [string, string, string][]) => [
  { id: "fire-shot", name: "Fire Shot", desc: "Tăng sức tấn công vũ khí thường", level: 1, maxLevel: 5, effect: "+4% weapon ATK / cấp", category: "common" as const },
  { id: "missile-shot", name: "Missile Shot", desc: "Tăng sức tấn công tên lửa", level: 1, maxLevel: 5, effect: "+4% missile ATK / cấp", category: "common" as const },
  { id: "concentration", name: "Concentration", desc: "Tăng độ chính xác và xác suất trúng", level: 1, maxLevel: 5, effect: "+3% accuracy / cấp", category: "common" as const },
  { id: "evasion-up", name: "Evasion Up", desc: "Nâng cao khả năng né tránh", level: 1, maxLevel: 5, effect: "+3 EVA / cấp", category: "common" as const },
  { id: "defense-up", name: "Defense Up", desc: "Tăng chỉ số phòng thủ", level: 1, maxLevel: 5, effect: "+3% DEF / cấp", category: "common" as const },
  ...skills.map(([id, name, desc]) => ({ id, name, desc, level: 1, maxLevel: 5, effect: "+8% hiệu lực / cấp", category: "gear" as const })),
]

export const PILOT_PROFILES = [
  { id: "marcus", name: "Marcus", age: 30, gender: "Nam", description: "Chiến binh dày dạn, chuyên gia vũ khí", specialty: "Weapons Specialist", gear: "A" as const, avatar: "/images/marcus-portrait.png", aircraftName: "Vanguard", armorType: "Heavy Armor", baseStats: { attack: 10, defense: 5, agility: 4, shield: 8, vision: 3 }, trail: ["+20% sát thương vũ khí Cannon", "+30% chỉ số trang bị ARMOR"], skills: commonSkills("A", [["siege-mode", "Siege Mode", "Chuyển sang chế độ pháo đài, tăng tầm bắn"], ["snare-shot", "Snare Shot", "Bắn đạn ghìm, làm chậm mục tiêu"], ["barrier", "Barrier", "Dựng khiên chắn cho phi cơ"]]) },
  { id: "valentine", name: "Valentine", age: 22, gender: "Nữ", description: "Phi công cứu hộ quyến rũ và tận tâm", specialty: "Rescue / Support", gear: "M" as const, avatar: "/images/valentine-portrait.png", aircraftName: "Aurora", armorType: "Support Armor", baseStats: { attack: 3, defense: 8, agility: 4, shield: 9, vision: 6 }, trail: ["+30% chỉ số trang bị ARMOR", "+30% DEF phi cơ", "+30% hiệu quả hồi máu đồng minh"], skills: commonSkills("M", [["healing-field", "Healing Field", "Tạo vùng hồi phục cho toàn hạm đội"], ["raging-fire", "Raging Fire", "Kích hoạt hỏa lực hỗ trợ"], ["full-recovery", "Full Recovery", "Hồi phục mạnh cho một phi cơ"]]) },
  { id: "alviss", name: "Alviss", age: 24, gender: "Nam", description: "Chiến thuật gia với đôi mắt như diều hâu", specialty: "Tactical Interceptor", gear: "I" as const, avatar: "/images/alviss-portrait.png", aircraftName: "Falcon", armorType: "Light Armor", baseStats: { attack: 11, defense: 3, agility: 12, shield: 2, vision: 2 }, trail: ["+10% chỉ số trang bị WEAPON", "+30% chỉ số MISSILE", "+10% chỉ số ENGINE"], skills: commonSkills("I", [["frenzy", "Frenzy", "Tăng tốc độ khai hỏa và sát thương"], ["overbooster", "Overbooster", "Đẩy động cơ vượt giới hạn"], ["berserker", "Berserker", "Tăng sức mạnh khi HP thấp"]]) },
  { id: "eric", name: "Eric", age: 22, gender: "Nam", description: "Phi công điềm đạm, thiên tài điều khiển oanh tạc cơ", specialty: "Aircraft Specialist", gear: "B" as const, avatar: "/images/eric-portrait.png", aircraftName: "Hammerfall", armorType: "Siege Armor", baseStats: { attack: 15, defense: 5, agility: 2, shield: 6, vision: 2 }, trail: ["+50% chỉ số trang bị MISSILE"], skills: commonSkills("B", [["ground-bombing", "Ground Bombing Mode", "Oanh tạc mặt đất, phá căn cứ"], ["air-bombing", "Air Bombing Mode", "Tập trung hỏa lực trên không"], ["big-boom", "Big Boom", "Đạn nổ diện rộng cực mạnh"]]) },
] as const

export const ITEM_DEFS: ItemDef[] = [
  // Weapons
  {
    id: "w_pulse",
    name: "Pulse Cannon",
    slot: "weapon",
    rarity: "common",
    bonus: { attack: 45 },
    cost: { credits: 500, alloy: 120 },
    desc: "Pháo xung cơ bản, ổn định.",
  },
  {
    id: "w_rail",
    name: "Rail Driver",
    slot: "weapon",
    rarity: "rare",
    bonus: { attack: 95, evasion: -4 },
    cost: { credits: 1400, alloy: 320, crystal: 20 },
    desc: "Pháo ray xuyên giáp, sát thương cao.",
  },
  {
    id: "w_plasma",
    name: "Plasma Lance",
    slot: "weapon",
    rarity: "epic",
    bonus: { attack: 165, energy: 20 },
    cost: { credits: 3200, alloy: 620, crystal: 60 },
    desc: "Thương plasma nung chảy giáp địch.",
  },
  {
    id: "w_singularity",
    name: "Singularity Core",
    slot: "weapon",
    rarity: "legendary",
    bonus: { attack: 260, speed: 10 },
    cost: { credits: 7200, alloy: 1200, crystal: 180 },
    desc: "Vũ khí kỳ dị, sát thương hủy diệt.",
  },
  // Missiles
  {
    id: "m_swarm",
    name: "Swarm Pods",
    slot: "missile",
    rarity: "rare",
    bonus: { attack: 60, speed: 6 },
    cost: { credits: 1100, alloy: 240 },
    desc: "Dàn tên lửa bầy đàn, đánh diện rộng.",
  },
  {
    id: "m_nova",
    name: "Nova Torpedo",
    slot: "missile",
    rarity: "epic",
    bonus: { attack: 120, defense: -10 },
    cost: { credits: 2800, alloy: 480, crystal: 45 },
    desc: "Ngư lôi Nova công phá công trình mạnh.",
  },
  // Armor
  {
    id: "a_plate",
    name: "Titan Plating",
    slot: "armor",
    rarity: "common",
    bonus: { hp: 300, defense: 30 },
    cost: { credits: 480, alloy: 200 },
    desc: "Giáp titan tiêu chuẩn.",
  },
  {
    id: "a_reactive",
    name: "Reactive Armor",
    slot: "armor",
    rarity: "rare",
    bonus: { hp: 550, defense: 70, speed: -5 },
    cost: { credits: 1600, alloy: 460, crystal: 25 },
    desc: "Giáp phản ứng nổ, giảm sát thương lớn.",
  },
  {
    id: "a_nanoweave",
    name: "Nanoweave Hull",
    slot: "armor",
    rarity: "epic",
    bonus: { hp: 900, defense: 120 },
    cost: { credits: 3400, alloy: 780, crystal: 70 },
    desc: "Vỏ nano tự tái tạo, cực bền.",
  },
  // Engine
  {
    id: "e_ion",
    name: "Ion Thruster",
    slot: "engine",
    rarity: "common",
    bonus: { speed: 20, evasion: 5 },
    cost: { credits: 520, alloy: 90 },
    desc: "Động cơ ion tăng tốc độ.",
  },
  {
    id: "e_warp",
    name: "Warp Drive",
    slot: "engine",
    rarity: "epic",
    bonus: { speed: 55, evasion: 18 },
    cost: { credits: 3000, alloy: 520, crystal: 55 },
    desc: "Động cơ warp, cơ động vượt trội.",
  },
  // Shield
  {
    id: "s_deflector",
    name: "Deflector Field",
    slot: "shield",
    rarity: "rare",
    bonus: { hp: 400, evasion: 10 },
    cost: { credits: 1300, alloy: 280, crystal: 30 },
    desc: "Khiên lệch hướng, tăng né.",
  },
  {
    id: "s_aegis",
    name: "Aegis Barrier",
    slot: "shield",
    rarity: "legendary",
    bonus: { hp: 750, defense: 90, evasion: 14 },
    cost: { credits: 6800, alloy: 1000, crystal: 160 },
    desc: "Khiên Aegis huyền thoại, phòng thủ tối thượng.",
  },
]

export const ITEM_MAP: Record<string, ItemDef> = Object.fromEntries(
  ITEM_DEFS.map((d) => [d.id, d]),
)

export const BUILDING_DEFS: Record<BuildingKey, BuildingDef> = {
  command: {
    key: "command",
    name: "Sở Chỉ Huy",
    desc: "Trung tâm căn cứ. Nâng cấp để mở khóa cấp công trình khác.",
    effect: "+ giới hạn cấp công trình, + uy tín",
    maxLevel: 30,
    baseCost: { credits: 2000, alloy: 600, crystal: 40 },
    costScale: 1.8,
  },
  hangar: {
    key: "hangar",
    name: "Nhà Chứa (Hangar)",
    desc: "Sửa chữa và bảo dưỡng phi thuyền. Tăng tốc độ hồi phục.",
    effect: "+ hồi durability mỗi ngày, + số Gear tối đa",
    maxLevel: 30,
    baseCost: { credits: 1200, alloy: 400 },
    costScale: 1.6,
  },
  factory: {
    key: "factory",
    name: "Nhà Máy Vũ Khí",
    desc: "Chế tạo vũ khí, trang bị. Giảm chi phí sản xuất.",
    effect: "- chi phí chế tạo trang bị",
    maxLevel: 30,
    baseCost: { credits: 1400, alloy: 500, crystal: 20 },
    costScale: 1.6,
  },
  reactor: {
    key: "reactor",
    name: "Lò Phản Ứng",
    desc: "Sản xuất năng lượng mỗi ngày cho căn cứ.",
    effect: "+ Năng lượng / ngày",
    maxLevel: 30,
    baseCost: { credits: 900, alloy: 260 },
    costScale: 1.5,
  },
  refinery: {
    key: "refinery",
    name: "Xưởng Luyện Kim",
    desc: "Khai thác & tinh luyện hợp kim mỗi ngày.",
    effect: "+ Hợp kim / ngày",
    maxLevel: 30,
    baseCost: { credits: 900, alloy: 200 },
    costScale: 1.5,
  },
  barracks: {
    key: "barracks",
    name: "Doanh Trại",
    desc: "Tăng giới hạn quân số cho hạm đội viễn chinh.",
    effect: "+ giới hạn quân số",
    maxLevel: 30,
    baseCost: { credits: 1100, alloy: 340 },
    costScale: 1.55,
  },
  turret: {
    key: "turret",
    name: "Tháp Phòng Thủ",
    desc: "Phòng thủ căn cứ trước phản kích của địch.",
    effect: "+ phòng thủ căn cứ",
    maxLevel: 30,
    baseCost: { credits: 800, alloy: 420, crystal: 15 },
    costScale: 1.5,
  },
  shipyard: {
    key: "shipyard",
    name: "Xưởng Đóng Tàu",
    desc: "Đóng phi thuyền mới nhanh & rẻ hơn.",
    effect: "- chi phí đóng Gear, + Gear tối đa",
    maxLevel: 30,
    baseCost: { credits: 1600, alloy: 560, crystal: 30 },
    costScale: 1.7,
  },
  finance: {
    key: "finance",
    name: "Trung Tâm Tài Chính",
    desc: "Quản lý ngân khố và đầu tư liên hành tinh.",
    effect: "+250 credits/ngày mỗi cấp",
    maxLevel: 30,
    baseCost: { credits: 1500, alloy: 300 },
    costScale: 1.45,
  },
  alliance: {
    key: "alliance",
    name: "Khu Liên Hợp Liên Minh",
    desc: "Cảng neo đậu chung của các đồng minh.",
    effect: "+1 sức chứa hạm đội mỗi cấp",
    maxLevel: 30,
    baseCost: { credits: 2500, alloy: 900, crystal: 40 },
    costScale: 1.5,
  },
  residential: {
    key: "residential",
    name: "Khu Dân Cư",
    desc: "Nhà ở cho di dân, nền tảng của nhân lực và quân số.",
    effect: "+0.5% tăng dân số, +60 quân số, +100 credits/ngày mỗi cấp",
    maxLevel: 30,
    baseCost: { credits: 1200, alloy: 500 },
    costScale: 1.42,
  },
  trade: {
    key: "trade",
    name: "Khu Giao Dịch",
    desc: "Chợ liên sao trao đổi hàng hóa và khoáng sản.",
    effect: "+400 credits, +40 hợp kim, +1 tinh thể/ngày mỗi cấp",
    maxLevel: 30,
    baseCost: { credits: 2200, alloy: 400, crystal: 20 },
    costScale: 1.5,
  },
  entertainment: {
    key: "entertainment",
    name: "Khu Vui Chơi",
    desc: "Giải trí, sòng bạc và đấu trường mô phỏng.",
    effect: "+500 credits/ngày mỗi cấp",
    maxLevel: 30,
    baseCost: { credits: 1800, alloy: 350 },
    costScale: 1.48,
  },
}

export const BUILDING_ORDER: BuildingKey[] = [
  "command",
  "hangar",
  "shipyard",
  "factory",
  "reactor",
  "refinery",
  "barracks",
  "turret",
  "finance",
  "alliance",
  "residential",
  "trade",
  "entertainment",
]

export const MAX_BUILDING_LEVEL = 30

export const DISTRICT_ORDER: DistrictKey[] = ["finance", "service", "industry", "power", "repair", "shipbuilding"]

export const DISTRICT_DEFS: Record<DistrictKey, { name: string; desc: string; perHundred: string }> = {
  finance: { name: "Tài chính", desc: "Credits / ngày", perHundred: "+50 credits/ngày" },
  service: { name: "Dịch vụ", desc: "Tinh thể / ngày", perHundred: "+1 tinh thể/ngày" },
  industry: { name: "Công nghiệp", desc: "Hợp kim / ngày", perHundred: "+5 hợp kim/ngày" },
  power: { name: "Điện lực / Lò phản ứng", desc: "Năng lượng / ngày", perHundred: "+10 năng lượng/ngày" },
  repair: { name: "Sửa chữa", desc: "HP hồi / Gear / ngày", perHundred: "+1.000 HP/ngày" },
  shipbuilding: { name: "Đóng tàu", desc: "Giảm chi phí, + Gear tối đa", perHundred: "-100 chi phí, +1 Gear" },
}

export const MAIN_BASE_POPULATION = 100_000
export const CAPTURE_BASE_POPULATION = 10_000

export const SECTORS: Sector[] = [
  {
    id: "s1",
    name: "Vành Đai Helios",
    kind: "outpost",
    x: 22,
    y: 68,
    threat: 320,
    garrison: 40,
    reward: { credits: 900, alloy: 260, energy: 120 },
    troopReward: 30,
    captured: false,
    recommendedPower: 1800,
    faction: "Cướp Biển Vũ Trụ",
  },
  {
    id: "s2",
    name: "Trạm Khai Mỏ K-7",
    kind: "outpost",
    x: 40,
    y: 78,
    threat: 520,
    garrison: 60,
    reward: { credits: 1400, alloy: 520, crystal: 30 },
    troopReward: 45,
    captured: false,
    recommendedPower: 3200,
    faction: "Liên Minh Bion",
  },
  {
    id: "s3",
    name: "Pháo Đài Nebula",
    kind: "base",
    isMainBase: true,
    x: 58,
    y: 60,
    threat: 980,
    garrison: 120,
    reward: { credits: 3000, alloy: 900, crystal: 90, energy: 300 },
    troopReward: 90,
    captured: false,
    recommendedPower: 6500,
    faction: "Liên Minh Bion",
  },
  {
    id: "s4",
    name: "Cổng Không Gian Zeta",
    kind: "outpost",
    x: 35,
    y: 42,
    threat: 720,
    garrison: 80,
    reward: { credits: 1900, alloy: 640, crystal: 50 },
    troopReward: 60,
    captured: false,
    recommendedPower: 4400,
    faction: "Cướp Biển Vũ Trụ",
  },
  {
    id: "s5",
    name: "Căn Cứ Vệ Tinh Orion",
    kind: "base",
    isMainBase: true,
    x: 70,
    y: 40,
    threat: 1500,
    garrison: 160,
    reward: { credits: 4800, alloy: 1400, crystal: 140, energy: 500 },
    troopReward: 130,
    captured: false,
    recommendedPower: 9500,
    faction: "Đế Chế Arclight",
  },
  {
    id: "s6",
    name: "Vùng Tối Cygnus",
    kind: "outpost",
    x: 82,
    y: 62,
    threat: 1150,
    garrison: 110,
    reward: { credits: 3400, alloy: 1000, crystal: 100 },
    troopReward: 95,
    captured: false,
    recommendedPower: 7600,
    faction: "Đế Chế Arclight",
  },
  {
    id: "s7",
    name: "Tàu Mẹ ARCLIGHT PRIME",
    kind: "mothership",
    x: 84,
    y: 22,
    threat: 3200,
    garrison: 300,
    reward: { credits: 12000, alloy: 3200, crystal: 400, energy: 1500 },
    troopReward: 250,
    captured: false,
    recommendedPower: 18000,
    faction: "Đế Chế Arclight",
  },
  { id: "s8", name: "Trạm Aurora", kind: "outpost", x: 15, y: 48, threat: 460, garrison: 52, reward: { credits: 1100, alloy: 340 }, troopReward: 35, captured: false, recommendedPower: 2600, faction: "ANI" },
  { id: "s9", name: "Cổng BCU Delta", kind: "base", isMainBase: true, x: 28, y: 24, threat: 880, garrison: 105, reward: { credits: 2600, alloy: 740, crystal: 60 }, troopReward: 78, captured: false, recommendedPower: 5900, faction: "BCU" },
  { id: "s10", name: "Mỏ Lumen", kind: "outpost", x: 47, y: 30, threat: 640, garrison: 70, reward: { credits: 1700, alloy: 600, crystal: 35 }, troopReward: 55, captured: false, recommendedPower: 3900, faction: "NGC" },
  { id: "s11", name: "Pháo Đài Meridian", kind: "base", isMainBase: true, x: 62, y: 82, threat: 1280, garrison: 150, reward: { credits: 4100, alloy: 1250, crystal: 110 }, troopReward: 112, captured: false, recommendedPower: 8400, faction: "BCU" },
  { id: "s12", name: "Vành Đai Polaris", kind: "outpost", x: 76, y: 74, threat: 1020, garrison: 96, reward: { credits: 3000, alloy: 880, energy: 280 }, troopReward: 88, captured: false, recommendedPower: 7000, faction: "ANI" },
  { id: "s13", name: "Tàu Mẹ BCU RED COMET", kind: "mothership", x: 92, y: 48, threat: 3600, garrison: 340, reward: { credits: 14000, alloy: 3600, crystal: 460, energy: 1600 }, troopReward: 270, captured: false, recommendedPower: 21000, faction: "BCU" },
  { id: "s14", name: "Hành Lang Vesper", kind: "outpost", x: 52, y: 12, threat: 780, garrison: 84, reward: { credits: 2200, alloy: 700, crystal: 45 }, troopReward: 64, captured: false, recommendedPower: 5000, faction: "NGC" },
  { id: "s15", name: "Trạm Hậu Cần NGC", kind: "base", isMainBase: true, x: 88, y: 88, threat: 1780, garrison: 190, reward: { credits: 5600, alloy: 1600, crystal: 160, energy: 520 }, troopReward: 145, captured: false, recommendedPower: 10800, faction: "NGC" },
  { id: "s16", name: "Khe Nứt Epsilon", kind: "outpost", x: 12, y: 14, threat: 920, garrison: 100, reward: { credits: 2800, alloy: 820 }, troopReward: 72, captured: false, recommendedPower: 6100, faction: "NGC" },
  { id: "s17", name: "Căn Cứ Bastion", kind: "base", isMainBase: true, x: 40, y: 92, threat: 1450, garrison: 175, reward: { credits: 4500, alloy: 1400, crystal: 130 }, troopReward: 122, captured: false, recommendedPower: 9800, faction: "ANI" },
  { id: "s18", name: "Tàu Mẹ ANI SKY CROWN", kind: "mothership", x: 8, y: 28, threat: 3400, garrison: 310, reward: { credits: 13000, alloy: 3400, crystal: 420, energy: 1550 }, troopReward: 260, captured: false, recommendedPower: 19500, faction: "ANI" },
]

export const STARTING_GEAR_NAMES = ["Vanguard", "Aegis", "Falcon", "Oracle"]

/* ==========================================================================
   PHASE 1 — COMBAT DATA (VANGUARD GEAR, 3 SKILLS, 3 ENEMIES)
   ========================================================================== */

export const VANGUARD_SKILLS: CombatSkill[] = [
  {
    id: "basic-attack",
    name: "Pháo Năng Lượng Thường",
    nameEn: "Photon Blaster",
    desc: "Bắn loạt pháo photon cơ bản gây 100% sát thương và nạp lại 15 SP lõi năng lượng.",
    spCost: 0,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.0,
  },
  {
    id: "pulse-strike",
    name: "Xung Kích Quang",
    nameEn: "Pulse Strike",
    desc: "Tập trung năng lượng phóng chùm xung kích cực mạnh gây 150% sát thương trực tiếp.",
    spCost: 25,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.5,
  },
  {
    id: "armor-break",
    name: "Phá Giáp Cơ Khí",
    nameEn: "Armor Break",
    desc: "Bắn đạn xuyên giáp gây 115% sát thương và phá hủy kết cấu giáp mục tiêu, giảm 35% phòng thủ trong 2 lượt.",
    spCost: 35,
    cooldown: 3,
    targetType: "single-enemy",
    damageMultiplier: 1.15,
    defenseReduction: 0.35,
    effectDuration: 2,
  },
  {
    id: "emergency-guard",
    name: "Lá Chắn Khẩn Cấp",
    nameEn: "Emergency Guard",
    desc: "Kích hoạt trường lực từ trường khẩn cấp, giảm 50% mọi sát thương nhận vào trong 2 lượt tiếp theo.",
    spCost: 30,
    cooldown: 4,
    targetType: "self",
    damageReduction: 0.5,
    effectDuration: 2,
  },
]

export const VANGUARD_INITIAL_UNIT: CombatUnit = {
  id: "player-vanguard",
  name: "Vanguard Gear",
  title: "Chiến Cơ Tiên Phong Vũ Trụ",
  gearType: "vanguard",
  isPlayer: true,
  hp: 1250,
  maxHp: 1250,
  sp: 100,
  maxSp: 100,
  attack: 145,
  defense: 75,
  speed: 85,
  statusEffects: [],
  skills: VANGUARD_SKILLS,
  skillCooldowns: {},
  avatar: "/images/alviss-portrait.png",
}

export const ENEMIES_DATA: Record<EnemyEncounterType, CombatUnit> = {
  "scout-drone": {
    id: "enemy-scout-drone",
    name: "Drone Trinh Sát",
    title: "Thiết Bị Bay Tốc Độ Cao",
    gearType: "scout-drone",
    archetype: "disruptor",
    isPlayer: false,
    hp: 680,
    maxHp: 680,
    sp: 60,
    maxSp: 60,
    attack: 105,
    defense: 35,
    speed: 110, // Hành động trước Vanguard nhờ tốc độ cao
    evasion: 15,
    critRate: 0.10,
    statusEffects: [],
    skills: [
      {
        id: "drone-blaster",
        name: "Tia Laser Quét",
        nameEn: "Scan Laser",
        desc: "Bắn chùm laser thăm dò tốc độ cao.",
        spCost: 0,
        cooldown: 0,
        targetType: "single-enemy",
        damageMultiplier: 1.0,
      },
      {
        id: "drone-emp",
        name: "Sóng Nhiễu Điện Từ EMP",
        nameEn: "EMP Pulse",
        desc: "Phóng sóng EMP làm nhiễu cảm biến, gây 115% sát thương và làm chậm 25 SPD trong 2 lượt.",
        spCost: 20,
        cooldown: 2,
        targetType: "single-enemy",
        damageMultiplier: 1.15,
        statusToApply: {
          type: "emp-slow",
          name: "EMP Làm Chậm",
          desc: "Hệ thống động cơ bị quá nhiệt, giảm 25 Tốc độ (SPD)",
          duration: 2,
          value: 25,
          stackType: "refresh",
          isDebuff: true,
        },
      },
      {
        id: "drone-jamming",
        name: "Phát Sóng Nhiễu ECM",
        nameEn: "ECM Jamming",
        desc: "Kích hoạt máy phát gây nhiễu radar, tăng 30% né tránh trong 2 lượt.",
        spCost: 15,
        cooldown: 3,
        targetType: "self",
        statusToApply: {
          type: "ecm-jamming",
          name: "Trường Nhiễu ECM",
          desc: "Tăng 30% khả năng né tránh mọi đòn tấn công",
          duration: 2,
          value: 30,
          stackType: "refresh",
        },
      },
    ],
    skillCooldowns: {},
  },
  "raider-mech": {
    id: "enemy-raider-mech",
    name: "Cơ Giáp Đột Kích",
    title: "Chiến Binh Tiền Tuyến Không Gian",
    gearType: "raider-mech",
    archetype: "aggressive",
    isPlayer: false,
    hp: 1150,
    maxHp: 1150,
    sp: 90,
    maxSp: 90,
    attack: 135,
    defense: 65,
    speed: 78,
    evasion: 5,
    critRate: 0.20,
    critDamage: 1.8,
    statusEffects: [],
    skills: [
      {
        id: "mech-autocannon",
        name: "Pháo Tự Động Siêu Tốc",
        nameEn: "Autocannon Burst",
        desc: "Loạt đạn bắn liên thanh tầm trung.",
        spCost: 0,
        cooldown: 0,
        targetType: "single-enemy",
        damageMultiplier: 1.0,
      },
      {
        id: "mech-missile",
        name: "Loạt Tên Lửa Định Hướng",
        nameEn: "Homing Missiles",
        desc: "Bắn 4 quả tên lửa gây 145% sát thương bùng nổ.",
        spCost: 30,
        cooldown: 2,
        targetType: "single-enemy",
        damageMultiplier: 1.45,
      },
      {
        id: "mech-plasma-burn",
        name: "Đạn Cháy Plasma",
        nameEn: "Plasma Incendiary",
        desc: "Bắn đạn plasma nhiệt hạch gây 110% sát thương và đốt cháy mục tiêu (DoT 15% ATK) trong 2 lượt.",
        spCost: 25,
        cooldown: 3,
        targetType: "single-enemy",
        damageMultiplier: 1.1,
        statusToApply: {
          type: "plasma-burn",
          name: "Cháy Plasma",
          desc: "Lửa plasma ăn mòn vỏ tàu, thiêu đốt 15% ATK ở đầu mỗi lượt",
          duration: 2,
          value: 0.15,
          dotPercent: 0.15,
          stackType: "refresh",
          isDebuff: true,
        },
      },
    ],
    skillCooldowns: {},
  },
  "siege-walker": {
    id: "enemy-siege-walker",
    name: "Pháo Đài Công Thành",
    title: "Cơ Giáp Trùm Hạng Nặng (Boss)",
    gearType: "siege-walker",
    archetype: "adaptive-boss",
    bossPhase: 1,
    isPlayer: false,
    hp: 2500,
    maxHp: 2500,
    sp: 120,
    maxSp: 120,
    attack: 175,
    defense: 105,
    speed: 52, // Tốc độ chậm nhưng phòng thủ và sát thương cực cao
    evasion: 2,
    critRate: 0.12,
    armorPenetration: 0.20,
    statusEffects: [],
    skills: [
      {
        id: "siege-cannon",
        name: "Đại Pháo Hạng Nặng",
        nameEn: "Heavy Siege Shell",
        desc: "Bắn đạn pháo hạt nhân công phá cực mạnh.",
        spCost: 0,
        cooldown: 0,
        targetType: "single-enemy",
        damageMultiplier: 1.1,
      },
      {
        id: "siege-barrage",
        name: "Mưa Pháo Hủy Diệt",
        nameEn: "Devastator Barrage",
        desc: "Xả hỏa lực hủy diệt toàn lực gây 165% sát thương.",
        spCost: 40,
        cooldown: 3,
        targetType: "single-enemy",
        damageMultiplier: 1.65,
      },
      {
        id: "siege-fortify",
        name: "Tăng Cường Vỏ Giáp",
        nameEn: "Titan Plating",
        desc: "Kích hoạt tấm chắn gia cố, giảm 40% sát thương nhận vào trong 2 lượt.",
        spCost: 35,
        cooldown: 4,
        targetType: "self",
        damageReduction: 0.4,
        effectDuration: 2,
        statusToApply: {
          type: "emergency-guard",
          name: "Vỏ Giáp Gia Cố Titan",
          desc: "Giảm 40% sát thương nhận vào trong 2 lượt",
          duration: 2,
          value: 0.4,
          stackType: "override",
        },
      },
      {
        id: "siege-acid",
        name: "Pháo Phun Acid Ăn Mòn",
        nameEn: "Acid Corrosion Mortar",
        desc: "Bắn đạn acid nung chảy kim loại, gây 110% sát thương, DoT 8% ATK và giảm 15% DEF mỗi tầng (tối đa 3 tầng).",
        spCost: 30,
        cooldown: 3,
        targetType: "single-enemy",
        damageMultiplier: 1.1,
        statusToApply: {
          type: "acid-corrosion",
          name: "Ăn Mòn Acid",
          desc: "Acid nung chảy giáp, giảm 15% DEF và rút máu mỗi lượt (cộng dồn tối đa 3 tầng)",
          duration: 3,
          value: 0.15,
          dotPercent: 0.08,
          stacks: 1,
          maxStacks: 3,
          stackType: "intensity",
          isDebuff: true,
        },
      },
      {
        id: "siege-charge",
        name: "Sạc Đại Pháo Tận Diệt",
        nameEn: "Charge Apocalypse Cannon",
        desc: "Nạp năng lượng hạt nhân toàn công suất! Lượt sau sẽ bắn đòn hủy diệt 240% sát thương xuyên thủng giáp!",
        spCost: 30,
        cooldown: 5,
        targetType: "self",
        statusToApply: {
          type: "charge-ultimate",
          name: "Đang Sạc Pháo Tận Diệt",
          desc: "CẢNH BÁO: Đòn hủy diệt sắp tung ra ở lượt kế tiếp!",
          duration: 1,
          value: 0,
        },
      },
    ],
    skillCooldowns: {},
  },
}

export const ENCOUNTER_INFO: {
  id: EnemyEncounterType
  name: string
  subtitle: string
  difficulty: "Dễ" | "Trung bình" | "Thử thách (Boss)"
  desc: string
  color: string
}[] = [
  {
    id: "scout-drone",
    name: "Drone Trinh Sát",
    subtitle: "Mục tiêu 01 — Trinh sát cơ động",
    difficulty: "Dễ",
    desc: "Tốc độ nhanh (Speed 110), ra đòn trước Vanguard. Máu mỏng, thích hợp để thử nghiệm các chuỗi kỹ năng.",
    color: "#38bdf8",
  },
  {
    id: "raider-mech",
    name: "Cơ Giáp Đột Kích",
    subtitle: "Mục tiêu 02 — Cơ giáp chiến đấu quy ước",
    difficulty: "Trung bình",
    desc: "Chỉ số cân bằng toàn diện, trang bị tên lửa định hướng. Yêu cầu tính toán SP và thời điểm phòng thủ hợp lý.",
    color: "#f59e0b",
  },
  {
    id: "siege-walker",
    name: "Pháo Đài Công Thành",
    subtitle: "Mục tiêu 03 — Trùm cơ giáp thiết giáp",
    difficulty: "Thử thách (Boss)",
    desc: "Máu dày (2,500 HP), giáp kiên cố (105 Giáp) và hỏa lực khủng khiếp. Cần dùng Phá Giáp Cơ Khí để hạ gục.",
    color: "#ef4444",
  },
]

/* ==========================================================================
   PHASE 3 — NEW GEAR CLASSES (FALCON & AEGIS)
   ========================================================================== */

import type { ArmoryShopItem, CampaignSector, StarfrontGearClassDef, StarfrontGearId } from "./types"

export const FALCON_SKILLS: CombatSkill[] = [
  {
    id: "basic-attack",
    name: "Tia Laser Kép Siêu Tốc",
    nameEn: "Twin Rapid Lasers",
    desc: "Bắn hai chùm laser liên hoàn gây 100% sát thương và nạp lại 15 SP.",
    spCost: 0,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.0,
  },
  {
    id: "falcon-dash",
    name: "Lướt Vô Ảnh",
    nameEn: "Ghost Dash",
    desc: "Gia tốc né tránh cực đại, phóng luồng hạt gây 125% sát thương và kích hoạt lá chắn tàng hình giảm 40% sát thương nhận trong 2 lượt.",
    spCost: 30,
    cooldown: 3,
    targetType: "single-enemy",
    damageMultiplier: 1.25,
    damageReduction: 0.4,
    effectDuration: 2,
  },
  {
    id: "falcon-barrage",
    name: "Mưa Laser Siêu Tốc",
    nameEn: "Laser Barrage",
    desc: "Xả chùm laser bão hòa tốc độ cao gây 165% sát thương cực lớn với tỉ lệ bạo kích vượt trội.",
    spCost: 35,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.65,
  },
  {
    id: "falcon-overdrive",
    name: "Quá Tải Lõi Động Cơ",
    nameEn: "Overdrive Surge",
    desc: "Bơm năng lượng tức thời vào khung cơ giáp, tạo trường xung chấn bảo hộ giảm 50% sát thương trong 2 lượt.",
    spCost: 25,
    cooldown: 4,
    targetType: "self",
    damageReduction: 0.5,
    effectDuration: 2,
  },
]

export const AEGIS_SKILLS: CombatSkill[] = [
  {
    id: "basic-attack",
    name: "Đại Pháo Hạng Nặng",
    nameEn: "Heavy Auto Cannon",
    desc: "Phóng đạn pháo công phá tầm gần gây 100% sát thương và nạp lại 15 SP.",
    spCost: 0,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.0,
  },
  {
    id: "aegis-shell",
    name: "Pháo Hạt Nhân Hủy Diệt",
    nameEn: "Nuclear Siege Shell",
    desc: "Tập trung năng lượng bắn đạn pháo hạt nhân công phá cực mạnh gây 180% sát thương xuyên thủng kết cấu.",
    spCost: 35,
    cooldown: 0,
    targetType: "single-enemy",
    damageMultiplier: 1.8,
  },
  {
    id: "armor-break",
    name: "Xung Chấn Phá Giáp",
    nameEn: "Armor Disruptor",
    desc: "Bắn sóng xung chấn cao tần làm nứt vỏ bọc địch, gây 120% sát thương và giảm 45% phòng ngự mục tiêu trong 2 lượt.",
    spCost: 30,
    cooldown: 3,
    targetType: "single-enemy",
    damageMultiplier: 1.2,
    defenseReduction: 0.45,
    effectDuration: 2,
  },
  {
    id: "emergency-guard",
    name: "Lá Chắn Titan Tuyệt Đối",
    nameEn: "Absolute Titan Barrier",
    desc: "Triển khai lưới điện từ trường nano siêu kiên cố, triệt tiêu 65% mọi sát thương nhận vào trong 2 lượt.",
    spCost: 35,
    cooldown: 4,
    targetType: "self",
    damageReduction: 0.65,
    effectDuration: 2,
  },
]

export const STARFRONT_GEAR_DEFS: Record<StarfrontGearId, StarfrontGearClassDef> = {
  vanguard: {
    id: "vanguard",
    name: "Vanguard Gear",
    nameEn: "Vanguard Fighter",
    role: "Cơ Giáp Cân Bằng (Balanced Striker)",
    desc: "Cơ giáp chiến đấu không gian đa dụng tiêu chuẩn. Cân bằng hoàn hảo giữa hỏa lực, khả năng bảo hộ và tốc độ cơ động.",
    color: "#06b6d4",
    avatar: "/images/alviss-portrait.png",
    passive: {
      id: "stable-core",
      name: "Lõi Năng Lượng Ổn Định",
      desc: "Hồi thêm +5 SP mỗi lượt (tổng +10 SP/lượt). Mỗi chu kỳ 3 lượt thi đấu, kích hoạt xung năng lượng giảm thêm 1 lượt hồi chiêu cho kỹ năng đang hồi.",
      shortDesc: "+5 SP/lượt · -1 CD mỗi 3 lượt",
      icon: "Zap",
      details: [
        { label: "Hồi Phục Năng Lượng", value: "+5 SP mỗi lượt (Tổng +10 SP)" },
        { label: "Chu Kỳ Giảm Hồi Chiêu", value: "Mỗi 3 lượt: -1 Lượt CD kỹ năng" },
      ],
    },
    baseStats: {
      hp: 1250,
      sp: 100,
      attack: 145,
      defense: 75,
      speed: 85,
    },
    growth: {
      hp: 80,
      sp: 10,
      attack: 12,
      defense: 6,
      speed: 2,
    },
    skills: VANGUARD_SKILLS,
  },
  falcon: {
    id: "falcon",
    name: "Falcon Gear",
    nameEn: "Falcon Interceptor",
    role: "Tiêm Kích Tốc Độ (Speed Infiltrator)",
    desc: "Chuyên cơ săn lùng tốc độ cao. Luôn giành quyền ra đòn trước tiên (Speed 125), hỏa lực sắc bén nhưng vỏ giáp nhẹ hơn.",
    color: "#a855f7",
    avatar: "/images/alviss-portrait.png",
    passive: {
      id: "mach-aero",
      name: "Khí Động Học Mach",
      desc: "Tỉ lệ né tránh bẩm sinh +15%. Đòn đánh bạo kích có 50% tỉ lệ kích hoạt thêm 1 đòn bắn phụ siêu tốc không tốn SP.",
      shortDesc: "+15% Né Tránh bẩm sinh · 50% Bắn bồi khi Bạo Kích",
      icon: "Wind",
      details: [
        { label: "Né Tránh Bẩm Sinh", value: "+15% Evasion vĩnh viễn" },
        { label: "Đòn Bắn Bồi Khí Động", value: "50% kích hoạt khi Bạo Kích (0 SP)" },
      ],
    },
    baseStats: {
      hp: 980,
      sp: 110,
      attack: 165,
      defense: 50,
      speed: 125,
    },
    growth: {
      hp: 60,
      sp: 12,
      attack: 15,
      defense: 4,
      speed: 4,
    },
    skills: FALCON_SKILLS,
  },
  aegis: {
    id: "aegis",
    name: "Aegis Gear",
    nameEn: "Aegis Siege Fortress",
    role: "Pháo Đài Bọc Thép (Heavy Siege Armor)",
    desc: "Cỗ máy chiến tranh hạng nặng bọc giáp titan. Máu cực dày, phòng thủ kiên cố và hỏa lực pháo hạt nhân khủng khiếp.",
    color: "#f59e0b",
    avatar: "/images/alviss-portrait.png",
    passive: {
      id: "titan-reactive",
      name: "Giáp Phản Lực Titan",
      desc: "Khiên gai phản lại 20% sát thương nhận vào cho kẻ tấn công. Đồng thời kháng 50% hiệu ứng làm chậm (EMP Slow) và phá giáp (Armor Break).",
      shortDesc: "Phản 20% Sát Thương · Kháng 50% Làm Chậm / Phá Giáp",
      icon: "ShieldAlert",
      details: [
        { label: "Gai Phản Sát Thương", value: "Phản 20% sát thương nhận vào" },
        { label: "Kháng Bất Lợi", value: "Giảm 50% hiệu lực Phá Giáp & Làm Chậm" },
      ],
    },
    baseStats: {
      hp: 1800,
      sp: 90,
      attack: 175,
      defense: 120,
      speed: 60,
    },
    growth: {
      hp: 120,
      sp: 8,
      attack: 14,
      defense: 10,
      speed: 1,
    },
    skills: AEGIS_SKILLS,
  },
}

/* ==========================================================================
   PHASE 3 — CAMPAIGN SECTORS & MISSIONS (BẢN ĐỒ CHIẾN DỊCH VŨ TRỤ)
   ========================================================================== */

export const CAMPAIGN_SECTORS: CampaignSector[] = [
  {
    id: "sector-1",
    name: "Vành Đai Tiểu Hành Tinh Asteroid",
    subtitle: "Vùng rìa không gian Orion — Mức đe dọa: Thấp",
    desc: "Khu vực biên giới với các mảnh vỡ thiên thạch dày đặc. Nơi các phi đội drone do thám xâm nhập trái phép.",
    color: "#38bdf8",
    threatLevel: "Cấp độ 1 - 3",
    missions: [
      {
        id: "m1-1",
        sectorId: "sector-1",
        sectorName: "Vành Đai Asteroid",
        order: 1,
        title: "Nhiệm Vụ 1-1: Tuần Tra Biên Giới",
        desc: "Thiết bị radar phát hiện Drone Trinh Sát đang quét trộm dữ liệu căn cứ. Hãy xuất kích đánh chặn ngay lập tức.",
        recommendedLevel: 1,
        encounterId: "scout-drone",
        firstClearReward: {
          credits: 300,
          exp: 100,
          itemId: "wpn_pulse_carbine",
        },
        repeatReward: {
          credits: 160,
          exp: 60,
        },
      },
      {
        id: "m1-2",
        sectorId: "sector-1",
        sectorName: "Vành Đai Asteroid",
        order: 2,
        title: "Nhiệm Vụ 1-2: Tín Hiệu Cầu Cứu SOS",
        desc: "Một tàu khảo sát bị kẹt giữa bãi đá thiên thạch và bị drone quấy rối liên tục. Đến giải cứu mục tiêu.",
        recommendedLevel: 2,
        encounterId: "scout-drone",
        reqMissionId: "m1-1",
        firstClearReward: {
          credits: 450,
          exp: 140,
          itemId: "shd_composite_plate",
        },
        repeatReward: {
          credits: 180,
          exp: 75,
        },
      },
      {
        id: "m1-3",
        sectorId: "sector-1",
        sectorName: "Vành Đai Asteroid",
        order: 3,
        title: "Nhiệm Vụ 1-3: Phá Vỡ Phong Tỏa Mỏ Quặng",
        desc: "Lực lượng Cơ Giáp Đột Kích đã đổ bộ thiết lập chốt chặn. Hãy hạ gục chỉ huy đột kích để giải phóng tuyến mỏ.",
        recommendedLevel: 3,
        encounterId: "raider-mech",
        reqMissionId: "m1-2",
        firstClearReward: {
          credits: 700,
          exp: 220,
          itemId: "eng_warp_thruster",
        },
        repeatReward: {
          credits: 360,
          exp: 140,
        },
      },
    ],
  },
  {
    id: "sector-2",
    name: "Tinh Vân Sấm Sét Plasma",
    subtitle: "Vùng dị thường từ trường — Mức đe dọa: Trung bình",
    desc: "Bão ion điện từ làm giảm tầm nhìn radar. Địch thiết lập các trạm radar xung kích ngầm tại đây.",
    color: "#a855f7",
    threatLevel: "Cấp độ 4 - 6",
    missions: [
      {
        id: "m2-1",
        sectorId: "sector-2",
        sectorName: "Tinh Vân Plasma",
        order: 1,
        title: "Nhiệm Vụ 2-1: Đột Kích Vùng Bão Ion",
        desc: "Xuyên qua màn bão từ, tiêu diệt cơ giáp cảnh giới của quân địch trước khi chúng báo động toàn khu vực.",
        recommendedLevel: 4,
        encounterId: "raider-mech",
        reqMissionId: "m1-3",
        firstClearReward: {
          credits: 900,
          exp: 280,
          itemId: "wpn_plasma_cutter",
        },
        repeatReward: {
          credits: 420,
          exp: 160,
        },
      },
      {
        id: "m2-2",
        sectorId: "sector-2",
        sectorName: "Tinh Vân Plasma",
        order: 2,
        title: "Nhiệm Vụ 2-2: Cắt Đứt Đường Dẫn Năng Lượng",
        desc: "Địch đang vận chuyển tinh thể năng lượng cao. Tiêu diệt toán đột kích áp tải để cướp tài nguyên.",
        recommendedLevel: 5,
        encounterId: "raider-mech",
        reqMissionId: "m2-1",
        firstClearReward: {
          credits: 1200,
          exp: 360,
          itemId: "shd_nano_barrier",
        },
        repeatReward: {
          credits: 480,
          exp: 190,
        },
      },
      {
        id: "m2-3",
        sectorId: "sector-2",
        sectorName: "Tinh Vân Plasma",
        order: 3,
        title: "Nhiệm Vụ 2-3: Quái Vật Thép Khởi Động",
        desc: "Một Pháo Đài Công Thành khổng lồ xuất hiện tại trung tâm tinh vân! Hãy dùng hỏa lực tối đa đánh sập nó.",
        recommendedLevel: 6,
        encounterId: "siege-walker",
        reqMissionId: "m2-2",
        firstClearReward: {
          credits: 1800,
          exp: 500,
          itemId: "wpn_hyper_railgun",
        },
        repeatReward: {
          credits: 900,
          exp: 320,
        },
      },
    ],
  },
  {
    id: "sector-3",
    name: "Quỹ Đạo Pháo Đài Bastion Core",
    subtitle: "Căn cứ đầu não địch — Mức đe dọa: Cực hạn",
    desc: "Tuyến phòng thủ kiên cố nhất với các lớp pháo phòng không hạt nhân và hạm đội trùm tối thượng.",
    color: "#ef4444",
    threatLevel: "Cấp độ 7 - 10+",
    missions: [
      {
        id: "m3-1",
        sectorId: "sector-3",
        sectorName: "Bastion Core",
        order: 1,
        title: "Nhiệm Vụ 3-1: Công Phá Cổng Ngoài",
        desc: "Đột nhập qua lớp phòng tuyến vệ tinh và tiêu diệt phi đội đột kích tinh nhuệ bảo vệ cổng chính.",
        recommendedLevel: 7,
        encounterId: "raider-mech",
        reqMissionId: "m2-3",
        firstClearReward: {
          credits: 2200,
          exp: 620,
          itemId: "eng_antimatter_drive",
        },
        repeatReward: {
          credits: 650,
          exp: 260,
        },
      },
      {
        id: "m3-2",
        sectorId: "sector-3",
        sectorName: "Bastion Core",
        order: 2,
        title: "Nhiệm Vụ 3-2: Đại Pháo Trùng Điệp",
        desc: "Pháo đài hạng nặng xả mưa đạn pháo hạt nhân. Cần phân bổ lượt phòng ngự khéo léo để tiếp cận.",
        recommendedLevel: 8,
        encounterId: "siege-walker",
        reqMissionId: "m3-1",
        firstClearReward: {
          credits: 2800,
          exp: 800,
          itemId: "shd_aegis_forcefield",
        },
        repeatReward: {
          credits: 1000,
          exp: 380,
        },
      },
      {
        id: "m3-3",
        sectorId: "sector-3",
        sectorName: "Bastion Core",
        order: 3,
        title: "Nhiệm Vụ 3-3: Quyết Chiến Trùm Tối Thượng",
        desc: "Tổng tấn công đánh sập lò phản ứng trung tâm Pháo Đài Bastion. Chiến thắng mang lại vinh quang tối cao!",
        recommendedLevel: 9,
        encounterId: "siege-walker",
        reqMissionId: "m3-2",
        firstClearReward: {
          credits: 5000,
          exp: 1500,
          itemId: "wpn_stellar_annihilator",
        },
        repeatReward: {
          credits: 1500,
          exp: 500,
        },
      },
    ],
  },
]

/* ==========================================================================
   PHASE 3 — ARMORY SHOP CATALOG (CHỢ QUÂN SỰ KHÔNG GIAN)
   ========================================================================== */

export const ARMORY_SHOP_ITEMS: ArmoryShopItem[] = [
  // TẦNG CƠ BẢN (MỞ NGAY TỪ ĐẦU)
  {
    item: {
      id: "shop_wpn_plasma_cutter",
      name: "Pháo Cắt Plasma Cao Áp Mk.II",
      slot: "weapon",
      rarity: "rare",
      desc: "Chùm plasma siêu nhiệt độ nung chảy kết cấu thép. Tăng mạnh sức tấn công và tốc độ ra đòn.",
      attackBonus: 36,
      speedBonus: 5,
      price: 850,
    },
    buyPrice: 850,
    tierName: "Cơ Bản (Mở ngay)",
  },
  {
    item: {
      id: "shop_shd_nano_barrier",
      name: "Khiên Nano Tự Phục Hồi V3",
      slot: "shield",
      rarity: "rare",
      desc: "Vi hạt nano tự liên kết hàn gắn các tổn thương trên vỏ bọc ngay lập tức.",
      defenseBonus: 30,
      hpBonus: 350,
      price: 900,
    },
    buyPrice: 900,
    tierName: "Cơ Bản (Mở ngay)",
  },
  {
    item: {
      id: "shop_eng_warp_thruster",
      name: "Động Cơ Gia Tốc Warp Mk.II",
      slot: "engine",
      rarity: "rare",
      desc: "Bộ đẩy phản lực thế hệ mới giúp cơ giáp lướt gió không gian tốc độ cao.",
      speedBonus: 20,
      attackBonus: 10,
      price: 1000,
    },
    buyPrice: 1000,
    tierName: "Cơ Bản (Mở ngay)",
  },

  // TẦNG SECTOR 1 (YÊU CẦU HOÀN THÀNH VÀNH ĐAI TIỂU HÀNH TINH ASTEROID)
  {
    item: {
      id: "shop_wpn_hyper_railgun",
      name: "Đại Pháo Ray Điện Từ Hyper Prime",
      slot: "weapon",
      rarity: "epic",
      desc: "Gia tốc đạn hạt nhân mini công phá cực đại giáp trụ mục tiêu.",
      attackBonus: 65,
      speedBonus: 8,
      defenseBonus: -5,
      price: 2200,
    },
    buyPrice: 2200,
    requiredSectorId: "sector-1",
    tierName: "Mở Khóa: Sector 1",
  },
  {
    item: {
      id: "shop_shd_aegis_forcefield",
      name: "Trường Lực Ion Aegis Tối Thượng",
      slot: "shield",
      rarity: "epic",
      desc: "Lưới chắn ion hóa triệt tiêu động năng đạn pháo và hồi năng lượng lõi.",
      defenseBonus: 52,
      hpBonus: 600,
      spBonus: 20,
      price: 2500,
    },
    buyPrice: 2500,
    requiredSectorId: "sector-1",
    tierName: "Mở Khóa: Sector 1",
  },

  // TẦNG SECTOR 2 (YÊU CẦU HOÀN THÀNH TINH VÂN PLASMA TỐI)
  {
    item: {
      id: "shop_eng_antimatter_drive",
      name: "Động Cơ Phản Vật Chất Dark Nova",
      slot: "engine",
      rarity: "epic",
      desc: "Nạp năng lượng phản vật chất vô hạn, tăng vượt trội Tốc độ, SP và HP.",
      speedBonus: 32,
      spBonus: 30,
      hpBonus: 200,
      price: 3200,
    },
    buyPrice: 3200,
    requiredSectorId: "sector-2",
    tierName: "Mở Khóa: Sector 2",
  },
  {
    item: {
      id: "shop_wpn_singularity_lance",
      name: "Thương Năng Lượng Điểm Kỳ Dị Singularity",
      slot: "weapon",
      rarity: "epic",
      desc: "Phóng chùm photon nén cực độ tạo lỗ đen vi mô nghiền nát vỏ tàu địch.",
      attackBonus: 75,
      speedBonus: 10,
      hpBonus: 150,
      price: 3500,
    },
    buyPrice: 3500,
    requiredSectorId: "sector-2",
    tierName: "Mở Khóa: Sector 2",
  },

  // TẦNG SECTOR 3 (YÊU CẦU HOÀN THÀNH PHÁO ĐÀI BASTION CORE — TỐI CỰC LEGENDARY)
  {
    item: {
      id: "shop_wpn_stellar_annihilator",
      name: "Súng Hủy Diệt Tinh Vân Prime",
      slot: "weapon",
      rarity: "legendary",
      desc: "Vũ khí chế tác từ lõi sao băng. Sức mạnh hủy diệt nguyên tử vô tiền khoáng hậu.",
      attackBonus: 95,
      speedBonus: 12,
      spBonus: 25,
      price: 6500,
    },
    buyPrice: 6500,
    requiredSectorId: "sector-3",
    tierName: "Hàng Tối Thượng: Sector 3 (Legendary)",
  },
  {
    item: {
      id: "shop_shd_stellar_bulwark",
      name: "Pháo Đài Bất Hoại Event Horizon",
      slot: "shield",
      rarity: "legendary",
      desc: "Khiên chắn trọng lực bẻ cong mọi loại đạn pháo và hồi phục cực hạn HP.",
      defenseBonus: 75,
      hpBonus: 950,
      spBonus: 35,
      price: 6000,
    },
    buyPrice: 6000,
    requiredSectorId: "sector-3",
    tierName: "Hàng Tối Thượng: Sector 3 (Legendary)",
  },
  {
    item: {
      id: "shop_eng_chronos_drive",
      name: "Động Cơ Dịch Chuyển Lượng Tử Chronos",
      slot: "engine",
      rarity: "legendary",
      desc: "Bẻ cong không-thời gian mang lại tốc độ tuyệt đỉnh và ưu thế ra đòn áp đảo.",
      speedBonus: 45,
      attackBonus: 20,
      spBonus: 40,
      price: 7000,
    },
    buyPrice: 7000,
    requiredSectorId: "sector-3",
    tierName: "Hàng Tối Thượng: Sector 3 (Legendary)",
  },
]

